BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blognotas/',include('blognotas.urls',namespace='blognotas')),
]

blognotas/urls.py
# Dumento url de blognotas

from django.urls import path
from . import views
app_name = 'blognotas'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),

]

blog_jmateo/models.py
from django.db import models # libreria basica
from django.utils import timezone #Librerias para utilizar las fechas

# Create your models here.
# Modelo basico con la estuctura de los datos que almacenaremos.
class Post(models.Model):
    # ELemos basicos de mi blog de notas:
    titulo = models.CharField(max_length=152)
    slug = models.SlugField(max_length=152)
    contenido = models.TextField()

    # Elementos con las fechas a mostrar:
    publicacion = models.DateTimeField(default=timezone.now)
    creacion = models.DateTimeField(auto_now_add=True)
    actualizacion = models.DateTimeField(auto_now=True)

    # Clase para el ordenamiento por fecha en que se publicaron los blos:
    class Meta:
        ordering = ['-publicacion']

    def __str__(self):
        return self.titulo

blognotas/models.py
from django.db import models # libreria basica
from django.utils import timezone #Librerias para utilizar las fechas
from django.contrib.auth.models import User

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(estado=Post.Status.PUBLISHED)

# Modelo basico con la estuctura de los datos que almacenaremos.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    # ELemos basicos de mi blog de notas:
    titulo = models.CharField(max_length=152)
    #slug = models.SlugField(unique=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blognotas')
    contenido = models.TextField()

    # Elementos con las fechas a mostrar:
    publicacion = models.DateTimeField(default=timezone.now)
    creacion = models.DateTimeField(auto_now_add=True)
    actualizacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=2, choices=Status.choices, default=Status.PUBLISHED)

    #Gestores de modelo
    objects = models.Manager()
    published = PublishedManager()
    # Clase para el ordenamiento por fecha en que se publicaron los blos:
    class Meta:
        ordering = ['-publicacion']

        # Ordenamiento del campo publicacion:
        indexes = [
            models.Index(fields=['-publicacion']),
        ]

    def __str__(self):
        return self.titulo

blognotas/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.http import Http404


# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request,'blog/post/list.html',
                  {'posts':posts})

# Segunda vista para mostar un solo de los post


def post_detail(request, id):
    try:
        post = Post.published.get(id=id)

    except Post.DoesNotExist:
        raise Http404("No Post fue encontrado en este caso.")
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

blognotas/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <title>{% block title %}{% endblock %}</title>

  <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>

<body>

  <div id="content">

    {% block content %}

    {% endblock %}

  </div>

  <div id="sidebar">

    <h2>My blog</h2>

    <p>This is my blog.</p>

  </div>

</body>

</html>

blognotas/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

  <h1>{{ post.title }}</h1>

  <p class="date">

    Published {{ post.publish }} by {{ post.author }}

  </p>

  {{ post.body|linebreaks }}

{% endblock %}

blognotas/templates/blog/post/list.html
{% extends "blog/../base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

  <h1>My Blog</h1>

  {% for post in posts %}

    <h2>

      <a href="{% url 'blog:post_detail' post.id %}">

        {{ post.title }}

      </a>

    </h2>

    <p class="date">

      Published {{ post.publish }} by {{ post.author }}

    </p>

    {{ post.body|truncatewords:30|linebreaks }}

  {% endfor %}

{% endblock %}